In [1]:
!pip install tf-nightly-2.0-preview



     |████████████████████████████████| 95.2MB 44kB/s 
     |████████████████████████████████| 450kB 67.7MB/s 
     |████████████████████████████████| 3.8MB 50.4MB/s 
     |████████████████████████████████| 81kB 12.9MB/s 
ERROR: google-colab 1.0.0 has requirement google-auth~=1.4.0, but you'll have google-auth 1.10.0 which is incompatible.
ERROR: tb-nightly 2.1.0a20191206 has requirement grpcio>=1.24.3, but you'll have grpcio 1.15.0 which is incompatible.
  Found existing installation: google-auth 1.4.2
    Uninstalling google-auth-1.4.2:
      Successfully uninstalled google-auth-1.4.2


In [1]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
print(tf.__version__)

2.0.0-dev20191002


In [2]:
dataset = tf.data.Dataset.range(10)
for val in dataset:
   print(val.numpy())

0
1
2
3
4
5
6
7
8
9


In [6]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(5, shift=1)
for window_dataset in dataset:
  for val in window_dataset:
    print(val.numpy(), end=" ")
  print()

0 1 2 3 4 
1 2 3 4 5 
2 3 4 5 6 
3 4 5 6 7 
4 5 6 7 8 
5 6 7 8 9 
6 7 8 9 
7 8 9 
8 9 
9 


In [7]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(5, shift=1, drop_remainder=True)
for window_dataset in dataset:
  for val in window_dataset:
    print(val.numpy(), end=" ")
  print()

0 1 2 3 4 
1 2 3 4 5 
2 3 4 5 6 
3 4 5 6 7 
4 5 6 7 8 
5 6 7 8 9 


In [10]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(5, shift=1, drop_remainder=True)
dataset = dataset.flat_map(lambda window: window.batch(5))
for window in dataset:
  print(window.numpy())


[0 1 2 3 4]
[1 2 3 4 5]
[2 3 4 5 6]
[3 4 5 6 7]
[4 5 6 7 8]
[5 6 7 8 9]


In [13]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(4, shift=1, drop_remainder=True)
dataset = dataset.flat_map(lambda window: window.batch(4))
dataset = dataset.map(lambda window: (window[:-1], window[-1:]))
for x,y in dataset:
  print(x.numpy(), y.numpy())

[0 1 2] [3]
[1 2 3] [4]
[2 3 4] [5]
[3 4 5] [6]
[4 5 6] [7]
[5 6 7] [8]
[6 7 8] [9]


In [14]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(5, shift=1, drop_remainder=True)
dataset = dataset.flat_map(lambda window: window.batch(5))
dataset = dataset.map(lambda window: (window[:-1], window[-1:]))
dataset = dataset.shuffle(buffer_size=10)
for x,y in dataset:
  print(x.numpy(), y.numpy())


[0 1 2 3] [4]
[5 6 7 8] [9]
[2 3 4 5] [6]
[1 2 3 4] [5]
[3 4 5 6] [7]
[4 5 6 7] [8]


In [16]:
dataset = tf.data.Dataset.range(20)
dataset = dataset.window(15, shift=1, drop_remainder=True)
dataset = dataset.flat_map(lambda window: window.batch(15))
dataset = dataset.map(lambda window: (window[:-1], window[-1:]))
dataset = dataset.shuffle(buffer_size=10)
dataset = dataset.batch(2).prefetch(1)
for x,y in dataset:
  print("x = ", x.numpy())
  print("y = ", y.numpy())


x =  [[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13]
 [ 5  6  7  8  9 10 11 12 13 14 15 16 17 18]]
y =  [[14]
 [19]]
x =  [[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
 [ 2  3  4  5  6  7  8  9 10 11 12 13 14 15]]
y =  [[15]
 [16]]
x =  [[ 3  4  5  6  7  8  9 10 11 12 13 14 15 16]
 [ 4  5  6  7  8  9 10 11 12 13 14 15 16 17]]
y =  [[17]
 [18]]
